version: "2"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
    - /root/web-clusters/nginx/conf.d:/etc/nginx/conf.d/
    - /root/web-clusters/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /root/web-clusters/nginx/nginx.conf.default:/etc/nginx/nginx.conf.default
    - /root/web-clusters/nginx/logs:/var/log/nginx
#    - /root/web-clusters/nginx/html:/usr/share/nginx/html
    ports:
    - "80:80"
    command: [nginx, '-g', 'daemon off;']
    networks:
    - web
  tomcat7.1:
    image: tomcat:7-alpine
    hostname: tomcat7.1
    volumes:
    - /root/web-clusters/7tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/7tomcats/logs:/usr/local/tomcat/logs
    - /root/web-clusters/7tomcats/webapps:/usr/local/tomcat/webapps
    command: ["catalina.sh", "run"]
    networks:
    - web
  tomcat7.2:
    image: tomcat:7-alpine
    hostname: tomcat7.2
    volumes:
    - /root/web-clusters/7tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/7tomcats/webapps:/usr/local/tomcat/webapps
    - /root/web-clusters/7tomcats/logs:/usr/local/tomcat/logs
    command: ["catalina.sh", "run"]
    networks:
    - web
  tomcat7.3:
    image: tomcat:7-alpine
    hostname: tomcat7.3
    volumes:
    - /root/web-clusters/7tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/7tomcats/webapps:/usr/local/tomcat/webapps
    - /root/web-clusters/7tomcats/logs:/usr/local/tomcat/logs
    command: ["catalina.sh", "run"]
    networks:
    - web
  tomcat8.1:
    image: tomcat:8-alpine
    hostname: tomcat8.1
    volumes:
    - /root/web-clusters/8tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/8tomcats/logs:/usr/local/tomcat/logs
    - /root/web-clusters/8tomcats/webapps:/usr/local/tomcat/webapps
    command: ["catalina.sh", "run"]
    networks:
    - web
  tomcat8.2:
    image: tomcat:8-alpine
    hostname: tomcat8.2
    volumes:
    - /root/web-clusters/8tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/8tomcats/webapps:/usr/local/tomcat/webapps
    - /root/web-clusters/8tomcats/logs:/usr/local/tomcat/logs
    command: ["catalina.sh", "run"]
    networks:
    - web
  tomcat8.3:
    image: tomcat:8-alpine
    hostname: tomcat8.3
    volumes:
    - /root/web-clusters/8tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/8tomcats/webapps:/usr/local/tomcat/webapps
    - /root/web-clusters/8tomcats/logs:/usr/local/tomcat/logs
    command: ["catalina.sh", "run"]
    networks:
    - web
networks:
  web:

