version: "2"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
    - /root/web-clusters/nginx/conf/conf.d:/etc/nginx/conf.d/
    - /root/web-clusters/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /root/web-clusters/nginx/logs:/var/log/nginx
    ports:
    - "80:80"
    command: [nginx, '-g', 'daemon off;']
    networks:
    - web
  7tomcat1:
    image: tomcat:7-alpine
    volumes:
    - /root/web-clusters/7tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/7tomcats/logs:/usr/local/tomcat/logs
    - /root/web-clusters/7tomcats/webapps:/usr/local/tomcat/webapps
    command: ["catalina.sh", "run"]
    networks:
    - web
  7tomcat2:
    image: tomcat:7-alpine
    volumes:
    - /root/web-clusters/7tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/7tomcats/webapps:/usr/local/tomcat/webapps
    - /root/web-clusters/7tomcats/logs:/usr/local/tomcat/logs
    command: ["catalina.sh", "run"]
    networks:
    - web
  7tomcat3:
    image: tomcat:7-alpine
    volumes:
    - /root/web-clusters/7tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/7tomcats/webapps:/usr/local/tomcat/webapps
    - /root/web-clusters/7tomcats/logs:/usr/local/tomcat/logs
    command: ["catalina.sh", "run"]
    networks:
    - web
  8tomcat1:
    image: tomcat:8-alpine
    volumes:
    - /root/web-clusters/8tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/8tomcats/logs:/usr/local/tomcat/logs
    - /root/web-clusters/8tomcats/webapps:/usr/local/tomcat/webapps
    command: ["catalina.sh", "run"]
    networks:
    - web
  8tomcat2:
    image: tomcat:8-alpine
    volumes:
    - /root/web-clusters/8tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/8tomcats/webapps:/usr/local/tomcat/webapps
    - /root/web-clusters/8tomcats/logs:/usr/local/tomcat/logs
    command: ["catalina.sh", "run"]
    networks:
    - web
  8tomcat3:
    image: tomcat:8-alpine
    volumes:
    - /root/web-clusters/8tomcats/conf:/usr/local/tomcat/conf
    - /root/web-clusters/8tomcats/webapps:/usr/local/tomcat/webapps
    - /root/web-clusters/8tomcats/logs:/usr/local/tomcat/logs
    command: ["catalina.sh", "run"]
    networks:
    - web
networks:
  web: