FROM java:jdk-alpine
MAINTAINER "qiuguochang"
ADD ./apache-tomcat-8.5.34.tar.gz /usr/local/
WORKDIR /usr/local/tomcat
COPY ./server.xml /usr/local/apache-tomcat-8.5.34/conf/
EXPOSE 8080
ENTRYPOINT ["/usr/local/apache-tomcat-8.5.34/bin/catalina.sh","run"]
